// =====================================================================================
// Copyright (c) 2016, Electric Power Research Institute (EPRI)
// All rights reserved.
//
// libcea2045 ("this software") is licensed under BSD 3-Clause license.
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// *  Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
//
// *  Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// *  Neither the name of EPRI nor the names of its contributors may
//    be used to endorse or promote products derived from this software without
//    specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
// INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
// OF SUCH DAMAGE.
//
// This EPRI software incorporates work covered by the following copyright and permission
// notices. You may not use these works except in compliance with their respective
// licenses, which are provided below.
//
// These works are provided by the copyright holders and contributors "as is" and any express or
// implied warranties, including, but not limited to, the implied warranties of merchantability
// and fitness for a particular purpose are disclaimed.
//
// This software relies on the following libraries and licenses:
//
// #########################################################################################
// Boost Software License, Version 1.0
// #########################################################################################
//
// * catch++ v1.2.1 (https://github.com/philsquared/Catch)
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// #########################################################################################
// MIT Licence
// #########################################################################################
//
// * easylogging++ Copyright (c) 2017 muflihun.com
//   https://github.com/easylogging/easyloggingpp
//   https://easylogging.muflihun.com
//   https://muflihun.com
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
/*
 * CEA2045Device.h
 *
 *  Created on: Mar 11, 2015
 *      Author: dupes
 */

#ifndef CEA2045DEVICE_H_
#define CEA2045DEVICE_H_


#include <memory>
#include <future>
#include <thread>
#include <time.h>
#include "../util/MSTimer.h"
#include "../util/Checksum.h"
#include "../linklayer/ILinkLayerComm.h"
#include "../message/CEA2045Message.h"
#include "../processmessage/IProcessMessage.h"
#include "message/QueryMaxPayload.h"
#include "message/QueryMessageTypeSupported.h"
#include "MessageHandler.h"

namespace cea2045 {

class CEA2045Device
{
private:
	std::unique_ptr<ILinkLayerComm> m_p_linkLayer;
	std::unique_ptr<IProcessMessage> m_p_processMessage;

	ILinkLayerComm *m_linkLayer;
	IProcessMessage *m_processMessage;

	unsigned int m_receiveTimeoutMS;

	std::thread *m_recvThread;

	MessageHandler m_requestHandler;

	bool m_shutdown;
	bool m_isRunning;

	MSTimer m_receiveTimer;
	MSTimer m_requestTimer;

	void processRequest(cea2045MessageHeader *messageHeader);
	void processResponse(cea2045MessageHeader *messageHeader, Message *response);
	bool processReceiveBuffer(ReceiveBuffer &receiveBuffer);

	bool waitForResponse(Message *message);
	bool waitForAck(Message *message);

	void recv();

protected:

public:

	CEA2045Device(ILinkLayerComm *linkLayer, IProcessMessage *processMessage, unsigned int receiveTimeoutMS = 500);

	CEA2045Device(std::unique_ptr<ILinkLayerComm> linkLayer, std::unique_ptr<IProcessMessage> processMessage, unsigned int receiveTimeoutMS = 500);

	virtual ~CEA2045Device();

	std::future<ResponseCodes> queueRequest(Message *request);

	std::future<ResponseCodes> queryMaxPayload();

	std::future<ResponseCodes> queryMessageTypeSupported(MessageCode messageCode, unsigned char messageType1, unsigned char messageType2);

	std::future<ResponseCodes> querySuportDataLinkMessages();
	std::future<ResponseCodes> querySuportIntermediateMessages();

	bool start();

	void shutDown();

	bool shuttingDown();

	void recvOne(ReceiveBuffer &receiveBuffer);
	void processNextRequest();
};

} // namespace cea2045

#endif /* CEA2045DEVICE_H_ */
